name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-cache
          key: ${{ runner.OS }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.OS }}-node-

      - name: Install Dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint
        continue-on-error: true

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test
